on:
  push:
    branches:
      - 'release/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-to-pantheon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.EXTERNAL_HOST }}" >> ~/.ssh/known_hosts

      - name: Push to repo
        run: |
          git remote add external "${{ secrets.EXTERNAL_REMOTE }}"
          git fetch external
          git checkout -b master external/master
          git merge ${{ github.head_ref || github.ref_name }}
          git push external master
