name: Autodeploy

on:
  push:
    branches:
      - develop

jobs:
  autodeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Merge develop into staging
        run: |
          git clone https://christian-theriot:${{secrets.GITHUB_TOKEN}}@github.com/christian-theriot/wp-portfolio.git  -b develop tmp
          cd tmp
          git config user.name $(git log --format=%an -n 1 $HEAD)
          git config user.email $(git log --format=%ae -n 1 $HEAD)
          git config pull.rebase false
          git pull origin develop staging
          git checkout staging
          git merge develop
          git push origin staging