name: Autodeploy

on:
  push:
    branches:
      - develop

jobs:
  autodeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Merge develop into staging
        run: |
          git config --global user.name "$(git log --format=%an -n 1 $HEAD)"
          git config --global user.email "$(git log --format=%an -n 1 $HEAD)"
          git fetch origin staging
          git checkout staging
          git merge develop
          git push origin staging