name: Autodeploy

on:
  push:
    branches:
      - develop

jobs:
  autodeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Merge develop into staging
        run: |
          USERNAME=$(git log --format=%an -n 1 $HEAD)
          EMAIL=$(git log --format=%an -n 1 $HEAD)
          git config --global user.name "$USERNAME"
          git config --global user.email "$EMAIL"
          git checkout staging
          git merge develop
          git push origin staging